web:
  build: .
  restart: always
  tty: true
  ports:
    - "8000:80"
  volumes:
    - .:/var/www/html
  links:
    - db:database
  environment:
    MYSQL_DATABASE: drupal
    MYSQL_USER: drupal
    MYSQL_PASSWORD: drupal
    MYSQL_HOST: database

db:
  image: mariadb:10
  environment:
    MYSQL_DATABASE: drupal
    MYSQL_USER: drupal
    MYSQL_PASSWORD: drupal
    MYSQL_ROOT_PASSWORD: drupal
  restart: always
  tty: true
